### ISSUE TITLE
Can't login with another account

### ISSUE THREAD

**Issue by 21Gxme** [Nantawat6510545543/KU-ACTIVE#133]
I tried logging in with a different account. But it can't be done. because another account that logged in before that becomes the last logged in account
<img width="1470" alt="image" src="https://github.com/Nantawat6510545543/KU-ACTIVE/assets/113856957/75d022c4-cf9f-4bcf-96e7-773a4e6b39dd">

**Comment by CondricNay** [comment]
Can you explain more? like list step by step what you did to get this bug

**Comment by 21Gxme** [comment]
https://github.com/Nantawat6510545543/KU-ACTIVE/assets/113856957/3bf8d4f9-5d1c-4ef9-897d-640388bb784f

You can see that in second tab I login by tantikon account and then I login tab 1 by bob account. after I login by bob account my second tab(that login by tantikon) it change to bob account instead

**Comment by CondricNay** [comment]
In Django, each user session is typically associated with a specific session ID, and by default, a user can only have one active session at a time. If a user logs in from another tab, it may override the existing session, and the user will be effectively logged out from the previous session.

https://stackoverflow.com/questions/31247213/django-different-sessions-on-different-tabs-unknown-amount-of-different-session

I suggest you use Private Mode if you want to test multiple users, because it will not affect your session.
