### ISSUE TITLE
Participant Limit of 0 does not working

### ISSUE THREAD

**Issue by J-Jullaphong** [Nantawat6510545543/KU-ACTIVE#137]
Why does this activity has 6 participants while the participant limit is 0?

<img width="430" alt="image" src="https://github.com/Nantawat6510545543/KU-ACTIVE/assets/111471511/1c11b66a-5422-46f8-a824-ef8c46dddee3">

**Comment by Nantawat6510545543** [comment]
The limit is 0, meaning no limit. Because some users don't want to limit the number of people participating. They have two options: no value or 0. And in the real world, no one creates an event that no one can participate in and then announces it.

this is my present code it may not show that 0 mean no limit
![image](https://github.com/Nantawat6510545543/KU-ACTIVE/assets/114897362/678ead6b-0622-48b5-a322-3793b739e292)

but here you can see old [version](https://github.com/Nantawat6510545543/KU-ACTIVE/blob/a2253ead50b38fddf8a3b16eab0a24c8c57daaa7/action/models/activity.py) 
![image](https://github.com/Nantawat6510545543/KU-ACTIVE/assets/114897362/f27d839f-74ba-414e-9c7e-dc17dfae2fab)

**Comment by J-Jullaphong** [comment]
In my opinion, this may cause confusion to users. If that is your reason, why don't just show the limit in the activities page as "none" instead of 0?

**Comment by Nantawat6510545543** [comment]
Thank you for your comments. It will be used for improvement.

**Comment by Nantawat6510545543** [comment]
problem solved; you may visit our [website](https://ku-active.fly.dev/action/) to see results.
